# This file is part of hellopyworld.
# https://github.com/scorphus/hellopyworld

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2018, Pablo S Blum <scorphus@gmail.com>

language: python

python:
    - "3.6"

install:
    # install python requirements
    - make setup

script:
    # run tests
    - make test
